### ISSUE TITLE
Anyway to use mocha.opts instead of env variable?

### ISSUE THREAD

**Issue by lchenay** [glenjamin/mocha-multi#10]
Will be more consistency with mocha.

**Comment by glenjamin** [comment]
We might be able to use the new `reporterOptions` feature in mocha. 

I'm happy to take a PR, but unlikely to have time to do this myself in the near future.

**Comment by glenjamin** [comment]
I think this might have been fixed by https://github.com/glenjamin/mocha-multi/pull/9

**Comment by seansfkelley** [comment]
It isn't, unfortunately. Using mocha.opts like so:

```
--reporter mocha-multi
--reporter-options spec=-
```

Doesn't work, because command-line `reporter-options` are passed through as simple string-string pairs, and mocha-multi expects a nested object that specifies a `stdout`.

I think mocha should support more complex command-line reporter options, but I also think it would make sense for mocha-multi to support reporter-options are are simple strings and assume it's a setting for `stdout`, with everything else left default.
